CREATE SEQUENCE TEMP_SEQ;

-- 시퀀스 객체를 처음 생성 후에는 NEXTVAL를 하여 값의 생성이 필요
SELECT TEMP_SEQ.NEXTVAL FROM DUAL;
SELECT TEMP_SEQ.CURRVAL FROM DUAL;

SELECT * FROM USER_SEQUENCES;

CREATE TABLE TEMP_T(
    id NUMBER,
    name VARCHAR2(10),
    gender CHAR(1) DEFAULT('M') CHECK(gender IN ('M','W'))
);

INSERT INTO TEMP_T VALUES(1, 'aaaa', 'M');
INSERT INTO TEMP_T VALUES(2, 'aaaa', 'M');
INSERT INTO TEMP_T VALUES(3, 'aaaa', 'M');
INSERT INTO TEMP_T VALUES(TEMP_SEQ.NEXTVAL, 'aaaa', 'M');

SELECT * FROM TEMP_T;

UPDATE TEMP_T
   SET ID = TEMP_SEQ.NEXTVAL;

-- 시스템 계정(ADMIN)으로 접속하여 실행해야 한다.
CREATE SYNONYM EMP FOR EMPLOYEES; -- USER1 계정에 SYNONYM 부여 권한을 준다.

GRANT CREATE SYNONYM TO USER1;

SELECT * FROM EMPLOYEES;
SELECT * FROM EMP;

-- 시스템 계정으로 전환 후 다음의 구문 실행
CREATE PUBLIC SYNONYM EMPS FOR USER1.EMPLOYEES;

SELECT * FROM USER1.EMPLOYEES;
SELECT * FROM EMPS;

SELECT * FROM USER_SYNONYMS;
SELECT * FROM ALL_SYNONYMS WHERE OWNER = 'PUBLIC';

/*
    1. TB_STUDENT 테이블의 데이터를 사용하여 
    휴학중인 학생의 정보를 저장하기 위한 테이블을 생성한다.
    (테이블 이름은 STUDENT_ABSENCE_TABLE 로 한다.)
    2.생성한 테이블은 학번, 학과코드, 이름, 담당교수 정보가 저장 될 수 있게한다.
    3. 생성한 테이블은 STD_ABC 이름의 동의어로도 사용할 수 있도록 만든다.
*/
CREATE TABLE STUDENT_ABSENCE_TABLE(
    id NUMBER NOT NULL,
    학번 VARCHAR2(10) NOT NULL,
    학과코드 VARCHAR2(10) NOT NULL,
    이름 VARCHAR2(50) NOT NULL,
    담당교수코드 VARCHAR2(10)
);
ALTER TABLE STUDENT_ABSENCE_TABLE ADD CONSTRAINT SAB_ID_PK PRIMARY KEY(ID);

INSERT INTO STUDENT_ABSENCE_TABLE(
    SELECT STU_ABSENCE_SEQ2.NEXTVAL AS ID,
           STUDENT_NO AS 학번,
           DEPARTMENT_NO AS 학과코드,
           STUDENT_NAME AS 이름,
           COACH_PROFESSOR_NO AS 담당교수코드
      FROM TB_STUDENT
     WHERE ABSENCE_YN='Y'
);

CREATE SEQUENCE STU_ABSENCE_SEQ2;

CREATE VIEW STUDENT_ABSENCE_VIEW AS
SELECT *
  FROM STUDENT_ABSENCE_TABLE;

SELECT * FROM STUDENT_ABSENCE_TABLE; 

CREATE SYNONYM STD_ABC FOR STUDENT_ABSENCE_TABLE;
CREATE SYNONYM V_STD_ABC FOR STUDENT_ABSENCE_VIEW;

SELECT * FROM STD_ABC;
SELECT * FROM V_STD_ABC;



SELECT * FROM TB_STUDENT WHERE ABSENCE_YN ='Y';
SELECT * FROM TB_CLASS;
DESC TB_STUDENT;




