-- 테이블을 직접 생성
CREATE TABLE STD_AVG_POINT(
      년도 VARCHAR2(4) NOT NULL,
      학번 VARCHAR2(10) NOU NULL,
      이름 VARCHAR2(50) NOT NULL,
      평균 NUMBER(3,2)
);
INSERT INTO STD_AVG_POINT(
    SELECT SUBSTR(G.TERM_NO,1,4) AS 년도,
           S.STUDENT_NO AS 학번,
           S.STUDENT_NAME AS 이름,
           AVG(G.POINT) AS 학점
      FROM TB_STUDENT S JOIN TB_GRADE G
        ON S.STUDENT_NO = G.STUDENT_NO
     WHERE G.TERM_NO LIKE '2009%'
     GROUP BY SUBSTR(G.TERM_NO,1,4), S.STUDENT_NO, S.STUDENT_NAME
);

-- 생성과 동시에 데이터 입력
CREATE TABLE TB_STU_TEMP2009 AS
    SELECT SUBSTR(G.TERM_NO,1,4) AS 년도,
           S.STUDENT_NO AS 학번,
           S.STUDENT_NAME AS 이름,
           AVG(G.POINT) AS 학점
      FROM TB_STUDENT S JOIN TB_GRADE G
        ON S.STUDENT_NO = G.STUDENT_NO
     WHERE G.TERM_NO LIKE '2009__'
     GROUP BY SUBSTR(G.TERM_NO,1,4), S.STUDENT_NO, S.STUDENT_NAME;


CREATE TABLE TB_DEPT_STU_PRO AS
    SELECT D.DEPARTMENT_NO AS 학과코드,
           D.DEPARTMENT_NAME AS 학과명,
           COUNT(S.STUDENT_NO) AS "학생 인원수",
           COUNT(P.PROFESSOR_NO) AS "교수 인원수"
      FROM TB_DEPARTMENT D JOIN TB_STUDENT S
        ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
      JOIN TB_PROFESSOR P
        ON D.DEPARTMENT_NO = P.DEPARTMENT_NO
     GROUP BY D.DEPARTMENT_NO, D.DEPARTMENT_NAME;     
     
 SELECT D.DEPARTMENT_NO AS 학과코드,
        D.DEPARTMENT_NAME AS 학과명,
        COUNT(DISTINCT S.STUDENT_NO) AS "학생 인원수",
        COUNT(DISTINCT P.PROFESSOR_NO) AS "교수 인원수"
      FROM TB_DEPARTMENT D JOIN TB_STUDENT S
        ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
      JOIN TB_PROFESSOR P
        ON D.DEPARTMENT_NO = P.DEPARTMENT_NO
     GROUP BY D.DEPARTMENT_NO, D.DEPARTMENT_NAME;   

 
 
SELECT * FROM TB_STUDENT WHERE DEPARTMENT_NO = 1;
SELECT * FROM TB_DEPT_STU_PRO;

/*
VIEW 로 만들기
*/
CREATE VIEW V_STD_AVG_POINT AS 
SELECT SUBSTR(G.TERM_NO,1,4) AS 년도,
       S.STUDENT_NO AS 학번,
       S.STUDENT_NAME AS 이름,
       AVG(G.POINT) AS 학점
  FROM TB_STUDENT S JOIN TB_GRADE G
    ON S.STUDENT_NO = G.STUDENT_NO
 WHERE G.TERM_NO LIKE '2009__'
 GROUP BY SUBSTR(G.TERM_NO,1,4), S.STUDENT_NO, S.STUDENT_NAME;

CREATE OR REPLACE FORCE VIEW V_DEPT_STD_PRO_COUNT AS
SELECT D.DEPARTMENT_NO AS 학과코드,
    D.DEPARTMENT_NAME AS 학과명,
    COUNT(DISTINCT S.STUDENT_NO) AS "학생 인원수",
    COUNT(DISTINCT P.PROFESSOR_NO) AS "교수 인원수"
  FROM TB_DEPARTMENT D JOIN TB_STUDENT S
    ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
  JOIN TB_PROFESSOR P
    ON D.DEPARTMENT_NO = P.DEPARTMENT_NO
 GROUP BY D.DEPARTMENT_NO, D.DEPARTMENT_NAME
 ORDER BY 1
WITH READ ONLY;  

SELECT * FROM V_STD_AVG_POINT;
SELECT * FROM V_DEPT_STD_PRO_COUNT;

SELECT * FROM USER_VIEWS WHERE VIEW_NAME = 'V_STD_AVG_POINT';


CREATE TABLE SAMPLE_T (
    id NUMBER NOT NULL,
    name VARCHAR2(10),
    age NUMBER
);

INSERT INTO SAMPLE_T VALUES(1, '홍길동', 30);
INSERT INTO SAMPLE_T VALUES(2, NULL, 24);
INSERT INTO SAMPLE_T VALUES(3, '김정훈', NULL);

CREATE VIEW V_SAMPLE_T AS
SELECT id, name FROM SAMPLE_T;

CREATE VIEW V_SAMPLE_T2 AS
SELECT id, age FROM SAMPLE_T WHERE age BETWEEN 0 AND 100
WITH CHECK OPTION;

SELECT * FROM V_SAMPLE_T;
INSERT INTO V_SAMPLE_T VALUES(4, '박주원');

SELECT * FROM V_SAMPLE_T2;
INSERT INTO V_SAMPLE_T2 VALUES(5,32);
INSERT INTO V_SAMPLE_T2 VALUES(6,150);
